<?php
$data = array (
  0 => 
  array (
    'cat_id' => '1',
    'cat_name' => '中国书画',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '6',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '8',
  ),
  1 => 
  array (
    'cat_id' => '2',
    'cat_name' => '瓷器',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '6',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  2 => 
  array (
    'cat_id' => '3',
    'cat_name' => '油画',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '6',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  3 => 
  array (
    'cat_id' => '4',
    'cat_name' => '刺绣',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '6',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  4 => 
  array (
    'cat_id' => '5',
    'cat_name' => '奇石玉石',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '6',
    'sort_order' => '5',
    'has_children' => '2',
    'goods_num' => '1',
  ),
  5 => 
  array (
    'cat_id' => '39',
    'cat_name' => '木品雕刻',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '6',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  6 => 
  array (
    'cat_id' => '40',
    'cat_name' => '文玩礼品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '6',
    'sort_order' => '7',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  7 => 
  array (
    'cat_id' => '6',
    'cat_name' => '宝石',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '6',
    'sort_order' => '1',
    'has_children' => '17',
    'goods_num' => 0,
  ),
  8 => 
  array (
    'cat_id' => '7',
    'cat_name' => '奇石',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '14',
    'goods_num' => 0,
  ),
  9 => 
  array (
    'cat_id' => '8',
    'cat_name' => '玛瑙',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '6',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  10 => 
  array (
    'cat_id' => '9',
    'cat_name' => '翡翠',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '6',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  11 => 
  array (
    'cat_id' => '10',
    'cat_name' => '金沙王',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  12 => 
  array (
    'cat_id' => '11',
    'cat_name' => '砗磲',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  13 => 
  array (
    'cat_id' => '12',
    'cat_name' => '珊瑚玉',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  14 => 
  array (
    'cat_id' => '13',
    'cat_name' => '海洋玉髓',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  15 => 
  array (
    'cat_id' => '14',
    'cat_name' => '水晶',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  16 => 
  array (
    'cat_id' => '15',
    'cat_name' => '水胆玛瑙',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '8',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  17 => 
  array (
    'cat_id' => '16',
    'cat_name' => '金田黄玉',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '9',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  18 => 
  array (
    'cat_id' => '17',
    'cat_name' => '新疆和田玉',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  19 => 
  array (
    'cat_id' => '18',
    'cat_name' => '和田玉',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '11',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  20 => 
  array (
    'cat_id' => '19',
    'cat_name' => '台山玉',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '12',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  21 => 
  array (
    'cat_id' => '20',
    'cat_name' => '南非碧玉',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '13',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  22 => 
  array (
    'cat_id' => '21',
    'cat_name' => '彩玉',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '14',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  23 => 
  array (
    'cat_id' => '22',
    'cat_name' => '广绿玉',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '15',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  24 => 
  array (
    'cat_id' => '23',
    'cat_name' => '乌拉圭黄玉',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '16',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  25 => 
  array (
    'cat_id' => '24',
    'cat_name' => '晴隆玉',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '17',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  26 => 
  array (
    'cat_id' => '25',
    'cat_name' => '长江石',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  27 => 
  array (
    'cat_id' => '26',
    'cat_name' => '大化石',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  28 => 
  array (
    'cat_id' => '27',
    'cat_name' => '风凌石',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  29 => 
  array (
    'cat_id' => '28',
    'cat_name' => '戈壁石',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  30 => 
  array (
    'cat_id' => '29',
    'cat_name' => '草花石',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  31 => 
  array (
    'cat_id' => '30',
    'cat_name' => '彩陶石',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  32 => 
  array (
    'cat_id' => '31',
    'cat_name' => '鸡血石',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  33 => 
  array (
    'cat_id' => '32',
    'cat_name' => '天铁石',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '8',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  34 => 
  array (
    'cat_id' => '33',
    'cat_name' => '树化石',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '9',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  35 => 
  array (
    'cat_id' => '34',
    'cat_name' => '龟纹石',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  36 => 
  array (
    'cat_id' => '35',
    'cat_name' => '蛋白石',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '11',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  37 => 
  array (
    'cat_id' => '36',
    'cat_name' => '邑江石',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '12',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  38 => 
  array (
    'cat_id' => '37',
    'cat_name' => '青海石胆',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '13',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  39 => 
  array (
    'cat_id' => '38',
    'cat_name' => '松花石',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '14',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  40 => 
  array (
    'cat_id' => '41',
    'cat_name' => '手串',
    'measure_unit' => '',
    'parent_id' => '40',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '12',
    'goods_num' => 0,
  ),
  41 => 
  array (
    'cat_id' => '42',
    'cat_name' => '手把件',
    'measure_unit' => '',
    'parent_id' => '40',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  42 => 
  array (
    'cat_id' => '43',
    'cat_name' => '紫砂壶',
    'measure_unit' => '',
    'parent_id' => '40',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  43 => 
  array (
    'cat_id' => '44',
    'cat_name' => '其他',
    'measure_unit' => '',
    'parent_id' => '40',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '14',
    'goods_num' => 0,
  ),
  44 => 
  array (
    'cat_id' => '45',
    'cat_name' => '崖柏',
    'measure_unit' => '',
    'parent_id' => '41',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '6',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  45 => 
  array (
    'cat_id' => '46',
    'cat_name' => '砗磲',
    'measure_unit' => '',
    'parent_id' => '41',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '6',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  46 => 
  array (
    'cat_id' => '47',
    'cat_name' => '沉香',
    'measure_unit' => '',
    'parent_id' => '41',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '6',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  47 => 
  array (
    'cat_id' => '48',
    'cat_name' => '海南黄花梨',
    'measure_unit' => '',
    'parent_id' => '41',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '6',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  48 => 
  array (
    'cat_id' => '49',
    'cat_name' => '越南黄花梨',
    'measure_unit' => '',
    'parent_id' => '41',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '6',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  49 => 
  array (
    'cat_id' => '50',
    'cat_name' => '金丝楠木',
    'measure_unit' => '',
    'parent_id' => '41',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '6',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  50 => 
  array (
    'cat_id' => '51',
    'cat_name' => '老山檀',
    'measure_unit' => '',
    'parent_id' => '41',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '6',
    'sort_order' => '7',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  51 => 
  array (
    'cat_id' => '52',
    'cat_name' => '蜜蜡',
    'measure_unit' => '',
    'parent_id' => '41',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '6',
    'sort_order' => '8',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  52 => 
  array (
    'cat_id' => '53',
    'cat_name' => '楠木',
    'measure_unit' => '',
    'parent_id' => '41',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '6',
    'sort_order' => '9',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  53 => 
  array (
    'cat_id' => '54',
    'cat_name' => '小叶紫檀',
    'measure_unit' => '',
    'parent_id' => '41',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '6',
    'sort_order' => '10',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  54 => 
  array (
    'cat_id' => '55',
    'cat_name' => '橄榄',
    'measure_unit' => '',
    'parent_id' => '41',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '6',
    'sort_order' => '11',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  55 => 
  array (
    'cat_id' => '56',
    'cat_name' => '葡提',
    'measure_unit' => '',
    'parent_id' => '41',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '6',
    'sort_order' => '12',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  56 => 
  array (
    'cat_id' => '57',
    'cat_name' => '金沙王',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '6',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  57 => 
  array (
    'cat_id' => '58',
    'cat_name' => '海洋玉髓',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '6',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  58 => 
  array (
    'cat_id' => '59',
    'cat_name' => '金田黄玉',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '6',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  59 => 
  array (
    'cat_id' => '60',
    'cat_name' => '台山玉',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '6',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  60 => 
  array (
    'cat_id' => '61',
    'cat_name' => '广绿玉',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '6',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  61 => 
  array (
    'cat_id' => '62',
    'cat_name' => '古董',
    'measure_unit' => '',
    'parent_id' => '44',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '6',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  62 => 
  array (
    'cat_id' => '63',
    'cat_name' => '象牙雕件',
    'measure_unit' => '',
    'parent_id' => '44',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '6',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  63 => 
  array (
    'cat_id' => '64',
    'cat_name' => '竹雕',
    'measure_unit' => '',
    'parent_id' => '44',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '6',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  64 => 
  array (
    'cat_id' => '65',
    'cat_name' => '蜜蜡',
    'measure_unit' => '',
    'parent_id' => '44',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '6',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  65 => 
  array (
    'cat_id' => '66',
    'cat_name' => '陶瓷茶具',
    'measure_unit' => '',
    'parent_id' => '44',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '6',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  66 => 
  array (
    'cat_id' => '67',
    'cat_name' => '鼻烟壶',
    'measure_unit' => '',
    'parent_id' => '44',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '6',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  67 => 
  array (
    'cat_id' => '68',
    'cat_name' => '墨玉',
    'measure_unit' => '',
    'parent_id' => '44',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '6',
    'sort_order' => '7',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  68 => 
  array (
    'cat_id' => '69',
    'cat_name' => '橄榄',
    'measure_unit' => '',
    'parent_id' => '44',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '6',
    'sort_order' => '8',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  69 => 
  array (
    'cat_id' => '70',
    'cat_name' => '香',
    'measure_unit' => '',
    'parent_id' => '44',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '6',
    'sort_order' => '9',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  70 => 
  array (
    'cat_id' => '71',
    'cat_name' => '香炉',
    'measure_unit' => '',
    'parent_id' => '44',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '6',
    'sort_order' => '10',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  71 => 
  array (
    'cat_id' => '72',
    'cat_name' => '精油',
    'measure_unit' => '',
    'parent_id' => '44',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '6',
    'sort_order' => '11',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  72 => 
  array (
    'cat_id' => '73',
    'cat_name' => '烟嘴',
    'measure_unit' => '',
    'parent_id' => '44',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '6',
    'sort_order' => '12',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  73 => 
  array (
    'cat_id' => '74',
    'cat_name' => '茶饼',
    'measure_unit' => '',
    'parent_id' => '44',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '6',
    'sort_order' => '13',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  74 => 
  array (
    'cat_id' => '75',
    'cat_name' => '烟丝',
    'measure_unit' => '',
    'parent_id' => '44',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '6',
    'sort_order' => '14',
    'has_children' => '0',
    'goods_num' => 0,
  ),
);
?>